name: note_vision
description: "Capstone: Optical Music Recognition Mobile App."
publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter

  # Input
  camera: ^0.12.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.0.15
  file_picker: ^8.1.2
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.4
  archive: ^4.0.7

  # Basic preprocessing (pure Dart)
  image: ^4.8.0

  # State management & UI helpers
  provider: ^6.1.5+1
  # fluttertoast: ^8.2.8

    # TFLite
  tflite_flutter: ^0.12.1


  # MusicXML parsing + export
  xml: ^6.5.0
  share_plus: ^12.0.2

    # Storage & paths
  # path_provider: ^2.1.5
  # permission_handler: ^11.3.1
  # sqflite: ^2.3.3+1
  # path: ^1.9.0

    # PDF export
  pdf: ^3.11.1

    # State management & UI helpers
  # provider: ^6.1.2
  # fluttertoast: ^8.2.8
  
    # Future phases (commented until needed)
  # opencv_4: ^1.0.0              # Advanced CV (deskew, staff detection)
  # flutter_midi: ^0.0.1           # MIDI playback
  # flutter_svg: ^2.0.10+1         # SVG rendering (if using verovio)

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/models/omr_model.tflite
    - assets/models/best_int8.tflite
  fonts:
    - family: MaturaMTScriptCapitals
      fonts:
        - asset: assets/fonts/maturasc.ttf

